<#
  update-scripts.ps1 - refresh the PowerShell scripts that are built into
  IR Workbench (core/scripts.js).

  Why: a page opened from disk can't read other files on disk, so the app
  carries each script inside core/scripts.js as base64. The Client tab
  decodes it for "Download" / "Copy script" and wraps it for "Copy one-liner":
    iex ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("...")))
  Run this after you change any of the scripts below.

  Usage (from the IR-Workbench folder):
    .\tools\update-scripts.ps1
    .\tools\update-scripts.ps1 -SourceFolder C:\path\to\scripts
    .\tools\update-scripts.ps1 -AlsoWriteB64Files   # also write <name>_b64.ps1 next to each script

  To add a script: add a line to $Scripts below, then use its Key in
  tabs/client.js (App.tabs.client.scriptToolsHtml("key", ...)).
#>
param(
    [string]$SourceFolder = (Split-Path $PSScriptRoot -Parent),
    [switch]$AlsoWriteB64Files
)

# Key = the name the app uses; File = the script's file name in $SourceFolder.
$Scripts = @(
    @{ Key = "adtriage";    File = "adtriage.ps1" },
    @{ Key = "triagecheck"; File = "Invoke-TriageCheck.ps1" }
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$updated = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm") + " UTC"
$entries = @()

foreach ($s in $Scripts) {
    $path = Join-Path $SourceFolder $s.File
    if (-not (Test-Path $path)) {
        Write-Warning "Skipped $($s.Key): $path not found"
        continue
    }
    # Read the script; drop a UTF-8 BOM and the final line break(s).
    $text = [IO.File]::ReadAllText((Resolve-Path $path))
    $text = $text.TrimStart([char]0xFEFF).TrimEnd("`r", "`n")

    # UTF-8 bytes -> base64 (letters, digits, + / = only: safe inside JavaScript).
    $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($text))
    $entries += "  `"$($s.Key)`": { file: `"$($s.File)`", updated: `"$updated`",`n    b64: `"$b64`" }"
    Write-Output "  $($s.Key): $($s.File) ($($b64.Length) base64 characters)"

    if ($AlsoWriteB64Files) {
        $oneLiner = 'iex ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("' + $b64 + '")))'
        $b64Path = Join-Path (Split-Path (Resolve-Path $path)) ([IO.Path]::GetFileNameWithoutExtension($s.File) + "_b64.ps1")
        [IO.File]::WriteAllText($b64Path, $oneLiner + "`n")
        Write-Output "    wrote $b64Path"
    }
}

$js = @"
// scripts.js - GENERATED by tools/update-scripts.ps1. Do not edit by hand.
//
// PowerShell scripts built into the app, stored as base64 of their UTF-8
// text. Use them with App.scriptText(key) and App.scriptOneLiner(key)
// (core/export.js). To update: change the .ps1, then run
// .\tools\update-scripts.ps1

App.SCRIPTS = {
$($entries -join ",`n")
};
"@

$jsPath = Join-Path $root "core\scripts.js"
[IO.File]::WriteAllText($jsPath, $js + "`n")
Write-Output "Wrote $jsPath ($($entries.Count) script(s), updated $updated)"
